services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["/app/entrypoint.sh"]

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
