services:
  frontend:
    build:
      context: ./frontend
      args:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
    container_name: soclewebapp_frontend
    image: soclewebapp_frontend:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    container_name: soclewebapp_backend
    image: soclewebapp_backend:latest
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["/app/entrypoint.sh"]

  postgres:
    image: postgres:15
    restart: always
    container_name: soclewebapp_postgres
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
