services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: soclewebapp_keycloak
    command: start-dev --import-realm --http-enabled=true --hostname=${KC_URL} --http-port=${KC_PORT} --db=${KC_DB} --db-url=${KC_DB_URL} --db-username=${KC_USER} --db-password=${KC_PASSWORD}
    env_file:
      - .env
    ports:
      - "${KC_PORT}:${KC_PORT}"
    environment:
      - KEYCLOAK_ADMIN=${KC_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_USER}
      - KC_DB_PASSWORD=${KC_PASSWORD}
    volumes:
      - ./keycloak/realm-import:/opt/keycloak/data/import
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
    container_name: soclewebapp_frontend
    image: soclewebapp_frontend:latest
    env_file:
      - .env
    ports:
      - "${VITE_FRONTEND_PORT}:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    container_name: soclewebapp_backend
    image: soclewebapp_backend:latest
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["/app/entrypoint.sh"]

  postgres:
    image: postgres:15
    restart: always
    container_name: soclewebapp_postgres
    env_file:
      - .env
    volumes:
      - ./db/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${DB_REDIRECT_PORT}:${DB_PORT}"
